name: 'Deploy helm gloot'
description: 'Deploy helm gloot'
inputs:
  gcp_key:
    description: 'desc'
    required: true
  zone:
    required: true
    default: 'europe-west1'
  project:
    required: true
    default: 'gnog-dev-af5b'
  cluster:
    required: true
    default: 'gloot-cluster'
  repository:
    description: "never override this unless you know what you're doing"
    required: true
    default: "$GITHUB_REPOSITORY"
  oci_helm_repo:
    required: true
    default: 'oci://gcr.io/gloot-automation/gloot-chart/gloot-application'
  oci_chart_version:
    required: true
    default: '0.0.0-latest'  
  helm_version:
    required: true
    default: '3.9.0'
  helm_args:
    description: 'should look something like this: "-f /files/values.yaml --set image.tag=latest"'
    required: true
  helm_command:
    description: "never override this unless you know what you're doing (protip: you don't)"
    required: true
    default: "upgrade --atomic --wait --install $RELEASE_NAME $INPUT_OCI_HELM_REPO --version=$INPUT_OCI_CHART_VERSION --set application.repo=$REPOSITORY"
outputs:
  log_url:
    description: 'URL to GCP logs'
runs:
  using: 'docker'
  image: 'docker://gcr.io/gloot-automation/action-deploy-helm:latest'
  args:
    - ${{ inputs.gcp_key }}
    - ${{ inputs.gcp_key }}
    - ${{ inputs.zone }}
    - ${{ inputs.project }}
    - ${{ inputs.cluster }}
    - ${{ inputs.oci_helm_repo }}
    - ${{ inputs.oci_chart_version }}
    - ${{ inputs.helm_version }}
    - ${{ inputs.helm_args }}
    - ${{ inputs.helm_command }}
