name: 'Deploy helm gloot'
description: 'Deploy helm gloot'
inputs:
  gcp_key:
    description: 'desc'
    required: true
  zone:
    required: true
    default: 'europe-west1-b'
  project:
    required: true
    default: 'gnog-dev-af5b'
  gcs_helm_repo:
    required: true
    default: 'oci://eu.gcr.io/gnog-dev-af5b/gcf'
  helm_version:
    required: true
    default: '3.9.0'
  helm_command:
    description: "never override this unless you know what you're doing (protip: you don't)"
    required: true
    default: "push demo application.repo=$REPOSITORY"
outputs:
  log_url:
    description: 'URL to GCP logs'
runs:
  using: 'docker'
  image: 'eu.gcr.io/gnog-dev-af5b/gcf/europe-west1/helm-oci:oci'
  args:
    - ${{ inputs.gcp_key }}
    - ${{ inputs.gcp_key }}
    - ${{ inputs.zone }}
    - ${{ inputs.project }}
    - ${{ inputs.gcs_helm_repo }}
    - ${{ inputs.helm_version }}
    - ${{ inputs.helm_command }}
