name: CI-Deploy

on:
  push

jobs:
  build-publish-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    env: 
      DOCKER_IMAGE_GCR: gcr.io/gloot-automation/action-deploy-helm
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # setup gcloud   
    - name: Setup GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GKE_KEY }}
        create_credentials_file: true
    - run: gcloud auth configure-docker
    - name: Bump version and push tag
      id: version_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
    - name: Push image to GCR
      run: |
        docker build . -t $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }}
        docker push $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }}
    # Update 'latest' image if on master branch
    - name: Push and update latest image in GCR
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }} $DOCKER_IMAGE_GCR:latest
        docker push $DOCKER_IMAGE_GCR:latest
