name: CI-Deploy

on:
  push

jobs:
  build-publish-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    env: 
      DOCKER_IMAGE_GCR: eu.gcr.io/gnog-dev-af5b/gcf/europe-west1/helm-oci
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '320.0.0'
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
    - run: gcloud auth configure-docker
    - name: Bump version and push tag
      id: version_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
    - name: Push image to GCR
      run: |
        docker build . -t $DOCKER_IMAGE_GCR:oci
        docker push $DOCKER_IMAGE_GCR:oci
